# cache: bundler
language: objective-c

osx_image: xcode10
xcode_project: Cleanse.xcodeproj
xcode_scheme: Cleanse
xcode_sdk: iphonesimulator12.0

script:
  - xcodebuild test -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -enableCodeCoverage=YES -destination "platform=iOS Simulator,name=iPad Air 2"

before_install:
  - rvm use $RVM_RUBY_VERSION

install: bundle install -j4 --path vendor/bundle --without documentation test development
after_success: bundle exec slather
